_wandb:
    value:
        cli_version: 0.24.1
        e:
            nwrwdua1v8csf2hozpu75kfjto79un1k:
                args:
                    - --lambda_class
                    - "5e-1"
                codePath: MY_code/teachers.py
                codePathLocal: MY_code/teachers.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "361207922688"
                        used: "16935809024"
                email: mazya@post.bgu.ac.il
                executable: /home/mazya/.conda/envs/py310/bin/python
                git:
                    commit: 953b4ce8ec3020d89d0eff73c0576e29c96058fd
                    remote: https://github.com/ShlezingerLab/OTA_RIS.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-0db26ccb-fb10-7ce4-61bc-42fb5890a6c0
                host: ise-pheno-01.auth.ad.bgu.ac.il
                memory:
                    total: "134416195584"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: /home/mazya/OTA_RIS/MY_code/teachers.py
                python: CPython 3.10.19
                root: /home/mazya/OTA_RIS
                slurm:
                    array_job_id: "14192515"
                    array_task_count: "6"
                    array_task_id: "2"
                    array_task_max: "5"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "6"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: tirzar
                    job_cpus_per_node: "6"
                    job_end_time: "1770221678"
                    job_gid: "1945600513"
                    job_gpus: "1"
                    job_id: "14192518"
                    job_name: minn_train
                    job_nodelist: ise-pheno-01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1770183878"
                    job_uid: "343830305"
                    job_user: mazya
                    jobid: "14192518"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: ise-pheno-01
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/mazya
                    submit_host: cs-pheno-03.auth.ad.bgu.ac.il
                    task_pid: "3584851"
                    tasks_per_node: "3"
                    topology_addr: ise-pheno-01
                    topology_addr_pattern: node
                startedAt: "2026-02-04T05:44:50.789125Z"
                writerId: nwrwdua1v8csf2hozpu75kfjto79un1k
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 3
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
N_m:
    value: 9
N_r:
    value: 10
N_t:
    value: 20
batch_size:
    value: 256
channel_sampling_size:
    value: 6000
device:
    value: cuda
epochs:
    value: 30
lambda_class:
    value: 0.5
lr:
    value: 0.001
mode:
    value: debug
model_type:
    value: MyTeacher
num_classes:
    value: 10
power:
    value: 3
subset_size:
    value: 10000
teacher_suffix:
    value: testme_debug_lambda_class=0.5_yaniv_4.2
weight_decay:
    value: 1e-07
