_wandb:
    value:
        cli_version: 0.24.1
        e:
            l57rdaj4wmbux4jtsj5qznbuccaq8pia:
                args:
                    - --lambda_class
                    - "1e-1"
                codePath: MY_code/teachers.py
                codePathLocal: MY_code/teachers.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "361207922688"
                        used: "25115979776"
                email: mazya@post.bgu.ac.il
                executable: /home/mazya/.conda/envs/py310/bin/python
                git:
                    commit: fea6a423349a86c7a83c9a8142e1b9931d7a4621
                    remote: https://github.com/ShlezingerLab/OTA_RIS.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-2186f553-1b36-d679-02b5-40318200884b
                host: cs-pheno-07.auth.ad.bgu.ac.il
                memory:
                    total: "134413389824"
                os: Linux-5.14.0-570.55.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/mazya/OTA_RIS/MY_code/teachers.py
                python: CPython 3.10.19
                root: /home/mazya/OTA_RIS
                slurm:
                    array_job_id: "14148163"
                    array_task_count: "1"
                    array_task_id: "0"
                    array_task_max: "0"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "6"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: tirzar
                    job_cpus_per_node: "6"
                    job_end_time: "1770100576"
                    job_gid: "1945600513"
                    job_gpus: "1"
                    job_id: "14148163"
                    job_name: minn_train
                    job_nodelist: cs-pheno-07
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1770062776"
                    job_uid: "343830305"
                    job_user: mazya
                    jobid: "14148163"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cs-pheno-07
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/mazya
                    submit_host: slurm-login-01
                    task_pid: "2388795"
                    tasks_per_node: "3"
                    topology_addr: cs-pheno-07
                    topology_addr_pattern: node
                startedAt: "2026-02-02T20:06:29.014558Z"
                writerId: l57rdaj4wmbux4jtsj5qznbuccaq8pia
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
N_m:
    value: 9
N_r:
    value: 10
N_t:
    value: 20
batch_size:
    value: 256
channel_sampling_size:
    value: 10000
device:
    value: cuda
epochs:
    value: 50
lambda_class:
    value: 0.1
lr:
    value: 0.001
mode:
    value: full
model_type:
    value: MyTeacher
num_classes:
    value: 10
power:
    value: 3
subset_size:
    value: 60000
teacher_suffix:
    value: testme_full_lambda_class=0.1_parallel_wb
weight_decay:
    value: 1e-07
